app_host: 'https://eb9e56ab.ngrok.io'

encryption_key1: 'This is a key that is 256 bits!!'
encryption_key2: 'This is a key that is 256 bits!!'

default:
  environment: 'local'
  api_host: 'http://localhost:5678'

maestrano-uat:
  environment: 'local'
  api_host: 'http://localhost:5678'
